### Imports

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#import data file
df = pd.read_csv('Demographic_Data.csv')
df.head()

in-store  age  items   amount  region
0         0   37      4   281.03       2
1         0   35      2   219.51       2
2         1   45      3  1525.70       4
3         1   46      3   715.25       3
4         1   33      4  1937.50       1

# Working in IPython

## Help & Documentation in Python

In [5]:
#use ? to bring up documentation for Python commands
df.shape?

Type:        property
String form: <property object at 0x000002576A43C770>
Docstring:  
Return a tuple representing the dimensionality of the DataFrame.

See Also
--------
ndarray.shape

Examples
--------
>>> df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
>>> df.shape
(2, 2)

>>> df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4],
...                    'col3': [5, 6]})
>>> df.shape
(2, 3)


In [7]:
#use ?? to bring up source code
df.shape??

Type:        property
String form: <property object at 0x000002576A43C770>
Source:     
# df.shape.fget
@property
def shape(self) -> Tuple[int, int]:
    """
    Return a tuple representing the dimensionality of the DataFrame.

    See Also
    --------
    ndarray.shape

    Examples
    --------
    >>> df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4]})
    >>> df.shape
    (2, 2)

    >>> df = pd.DataFrame({'col1': [1, 2], 'col2': [3, 4],
    ...                    'col3': [5, 6]})
    >>> df.shape
    (2, 3)
    """
    return len(self.index), len(self.columns)


In [8]:
#use TAB to bring up list of available functions when you only know first few letters
df.shift

#you can also use TAB to show what options you have when importing

<bound method DataFrame.shift of        in-store  age  items   amount  region
0             0   37      4   281.03       2
1             0   35      2   219.51       2
2             1   45      3  1525.70       4
3             1   46      3   715.25       3
4             1   33      4  1937.50       1
...         ...  ...    ...      ...     ...
79995         1   71      3   558.82       1
79996         0   59      7  1932.00       3
79997         0   54      1   414.16       2
79998         1   49      4   335.32       1
79999         1   30      1   527.12       3

[80000 rows x 5 columns]>

In [9]:
df.shift?

Signature: df.shift(periods=1, freq=None, axis=0, fill_value=None) -> 'DataFrame'
Docstring:
Shift index by desired number of periods with an optional time `freq`.

When `freq` is not passed, shift the index without realigning the data.
If `freq` is passed (in this case, the index must be date or datetime,
or it will raise a `NotImplementedError`), the index will be
increased using the periods and the `freq`. `freq` can be inferred
when specified as "infer" as long as either freq or inferred_freq
attribute is set in the index.

Parameters
----------
periods : int
    Number of periods to shift. Can be positive or negative.
freq : DateOffset, tseries.offsets, timedelta, or str, optional
    Offset to use from the tseries module or time rule (e.g. 'EOM').
    If `freq` is specified then the index values are shifted but the
    data is not realigned. That is, use `freq` if you would like to
    extend the index when shifting and preserve the original data.
    If `freq` is specified as "i

In [10]:
#you can also use TAB with wildcard operator if you only know the ending
*Warning?

BytesWarning
DeprecationWarning
FutureWarning
ImportWarning
PendingDeprecationWarning
ResourceWarning
RuntimeWarning
SyntaxWarning
UnicodeWarning
UserWarning
Warning

In [11]:
str.*find*?

str.find
str.rfind

In [13]:
#to bring up a list of all commands you have previously executed in the nb, along with your comments
%history

#import data file
df = pd.read_csv('Demographic_Data.csv')
df.head()
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
#import data file
df = pd.read_csv('Demographic_Data.csv')
df.head()
#use ? to bring up documentation for Python commands
#use ? to bring up documentation for Python commands
df.shape?
df.shape()?
#use ?? to bring up source code
df.shape??
#use TAB to bring up list of available functions when you don't know
df.shift
df.shift?
#you can also use TAB with wildcard operator if you only know the ending
*Warning?
str.*find*?
%history
#to bring up a list of all commands you have previously executed in the nb, along with your comments
%history


## Line & Cell Magics

In [17]:
#if you get an error when trying to run code copied and pasted from, e.g. the internet 
%%paste
>>> def donothing(x):
...     return x

SyntaxError: invalid syntax (<ipython-input-17-d0b1c1716e88>, line 3)

In [18]:
#to execute canned script from saved py file
%run myscript_test.py

In [19]:
%run?

Docstring:
Run the named file inside IPython as a program.

Usage::

  %run [-n -i -e -G]
       [( -t [-N<N>] | -d [-b<N>] | -p [profile options] )]
       ( -m mod | file ) [args]

Parameters after the filename are passed as command-line arguments to
the program (put in sys.argv). Then, control returns to IPython's
prompt.

This is similar to running at a system prompt ``python file args``,
but with the advantage of giving you IPython's tracebacks, and of
loading all variables into your interactive namespace for further use
(unless -p is used, see below).

The file is executed in a namespace initially consisting only of
``__name__=='__main__'`` and sys.argv constructed as indicated. It thus
sees its environment as if it were being run as a stand-alone program
(except for sharing global objects such as previously imported
modules). But after execution, the IPython interactive namespace gets
updated with all variables defined in the program (except for __name__
and sys.argv). This allo

In [20]:
#timeit magic to determine execution time of a single line
%timeit L = [n ** 2 for n in range(1000)]

342 µs ± 4.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [29]:
%%timeit
#use %% for multi-line commands, this makes it a cell magic, important: cell magics must be first line 
L = []
for n in range(1000):
    L.append(n **2)

398 µs ± 2.96 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [27]:
%%writefile hellojupyter.py 
#writes contents of cell to separate file
x=10
y=20
z= x=y

Overwriting hellojupyter.py


In [28]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [30]:
%magic


IPython's 'magic' functions

The magic function system provides a series of functions which allow you to
control the behavior of IPython itself, plus a lot of system-type
features. There are two kinds of magics, line-oriented and cell-oriented.

Line magics are prefixed with the % character and work much like OS
command-line calls: they get as an argument the rest of the line, where
arguments are passed without parentheses or quotes.  For example, this will
time the given statement::

        %timeit range(1000)

Cell magics are prefixed with a double %%, and they are functions that get as
an argument not only the rest of the line, but also the lines below it in a
separate argument.  These magics are called with two arguments: the rest of the
call line and the body of the cell, consisting of the lines below the first.
For example::

        %%timeit x = numpy.random.randn((100, 100))
        numpy.linalg.svd(x)

will time the execution of the numpy svd routine, running the assignment 

In [31]:
#get info on magics using ?
%timeit?

Docstring:
Time execution of a Python statement or expression

Usage, in line mode:
  %timeit [-n<N> -r<R> [-t|-c] -q -p<P> -o] statement
or in cell mode:
  %%timeit [-n<N> -r<R> [-t|-c] -q -p<P> -o] setup_code
  code
  code...

Time execution of a Python statement or expression using the timeit
module.  This function can be used both as a line and cell magic:

- In line mode you can time a single-line statement (though multiple
  ones can be chained with using semicolons).

- In cell mode, the statement in the first line is used as setup code
  (executed but not timed) and the body of the cell is timed.  The cell
  body has access to any variables created in the setup code.

Options:
-n<N>: execute the given statement <N> times in a loop. If <N> is not
provided, <N> is determined so as to get sufficient accuracy.

-r<R>: number of repeats <R>, each consisting of <N> loops, and take the
best result.
Default: 7

-t: use time.time to measure the time, which is the default on Unix.
This f

## Input and Output History

In [32]:
#to output a list of all the input commands in your nb
print(In)

['', "#import data file\ndf = pd.read_csv('Demographic_Data.csv')\ndf.head()", 'import pandas as pd\nimport numpy as np\nimport matplotlib.pyplot as plt\nimport seaborn as sns', "#import data file\ndf = pd.read_csv('Demographic_Data.csv')\ndf.head()", '#use ? to bring up documentation for Python commands', "#use ? to bring up documentation for Python commands\nget_ipython().run_line_magic('pinfo', 'df.shape')", 'df.shape()?', "#use ?? to bring up source code\nget_ipython().run_line_magic('pinfo2', 'df.shape')", "#use TAB to bring up list of available functions when you don't know\ndf.shift", "get_ipython().run_line_magic('pinfo', 'df.shift')", "#you can also use TAB with wildcard operator if you only know the ending\nget_ipython().run_line_magic('psearch', '*Warning')", "get_ipython().run_line_magic('psearch', 'str.*find*')", "get_ipython().run_line_magic('history', '')", "#to bring up a list of all commands you have previously executed in the nb, along with your comments\nget_ipython(

In [33]:
Out

{3:    in-store  age  items   amount  region
 0         0   37      4   281.03       2
 1         0   35      2   219.51       2
 2         1   45      3  1525.70       4
 3         1   46      3   715.25       3
 4         1   33      4  1937.50       1,
 8: <bound method DataFrame.shift of        in-store  age  items   amount  region
 0             0   37      4   281.03       2
 1             0   35      2   219.51       2
 2             1   45      3  1525.70       4
 3             1   46      3   715.25       3
 4             1   33      4  1937.50       1
 ...         ...  ...    ...      ...     ...
 79995         1   71      3   558.82       1
 79996         0   59      7  1932.00       3
 79997         0   54      1   414.16       2
 79998         1   49      4   335.32       1
 79999         1   30      1   527.12       3
 
 [80000 rows x 5 columns]>,
 28: Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  

In [34]:
print(Out[3])

   in-store  age  items   amount  region
0         0   37      4   281.03       2
1         0   35      2   219.51       2
2         1   45      3  1525.70       4
3         1   46      3   715.25       3
4         1   33      4  1937.50       1


### Use Previous Outputs in Commands

In [35]:
#you can use Out[x] to interact with previous outputs
import math

In [36]:
math.sin(2)

0.9092974268256817

In [37]:
math.cos(2)

-0.4161468365471424

In [38]:
Out[36]**2 + Out[37]**2

1.0

In [39]:
#you can also access previous output using _
print(_)

1.0


## Debugging 

In [40]:
#just sample code to throw an error in next line
def func1(a, b):
    return a / bjj

def func2(x):
    a = x
    b = x - 1
    return func1(a, b)j

In [41]:
func2(1)

ZeroDivisionError: division by zero

In [42]:
%debug

> <ipython-input-40-586ccabd0db3>(2)func1()
      1 def func1(a, b):
----> 2     return a / b
      3 
      4 def func2(x):
      5     a = x



ipdb>  print(a)


1


ipdb>  print(b)


0


ipdb>  quit


In [43]:
%debug

> <ipython-input-40-586ccabd0db3>(2)func1()
      1 def func1(a, b):
----> 2     return a / b
      3 
      4 def func2(x):
      5     a = x



ipdb>  up


> <ipython-input-40-586ccabd0db3>(7)func2()
      3 
      4 def func2(x):
      5     a = x
      6     b = x - 1
----> 7     return func1(a, b)



ipdb>  print(x)


1


ipdb>  up


> <ipython-input-41-7cb498ea7ed1>(1)<module>()
----> 1 func2(1)



ipdb>  down


> <ipython-input-40-586ccabd0db3>(7)func2()
      3 
      4 def func2(x):
      5     a = x
      6     b = x - 1
----> 7     return func1(a, b)



ipdb>  quit


In [44]:
#you can turn on the function to automatically start the debugger when an excpetion is raised
%pdb

Automatic pdb calling has been turned ON


In [47]:
#to change how much information exception/error messages produce
#by default the mode is set to Context, you can also use Verbose 
%xmode Plain    

Exception reporting mode: Plain


In [48]:
func2(1)

ZeroDivisionError: division by zero

> <ipython-input-40-586ccabd0db3>(2)func1()
      1 def func1(a, b):
----> 2     return a / b
      3 
      4 def func2(x):
      5     a = x



ipdb>  list


      1 def func1(a, b):
----> 2     return a / b
      3 
      4 def func2(x):
      5     a = x
      6     b = x - 1
      7     return func1(a, b)



ipdb>  help



Documented commands (type help <topic>):
EOF    cl         disable  interact  next    psource  rv           undisplay
a      clear      display  j         p       q        s            unt      
alias  commands   down     jump      pdef    quit     skip_hidden  until    
args   condition  enable   l         pdoc    r        source       up       
b      cont       exit     list      pfile   restart  step         w        
break  continue   h        ll        pinfo   return   tbreak       whatis   
bt     d          help     longlist  pinfo2  retval   u            where    
c      debug      ignore   n         pp      run      unalias    

Miscellaneous help topics:
exec  pdb



ipdb>  q


## Check Performance Metics on Code 

In [49]:
def sum_of_lists(N):
    total = 0
    for i in range(5):
        L = [j ^ (j >> i) for j in range(N)]
        total += sum(L)
    return total

In [50]:
%prun sum_of_lists(1000)

         14 function calls in 0.001 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        5    0.001    0.000    0.001    0.000 <ipython-input-49-f105717832a2>:4(<listcomp>)
        5    0.000    0.000    0.000    0.000 {built-in method builtins.sum}
        1    0.000    0.000    0.001    0.001 {built-in method builtins.exec}
        1    0.000    0.000    0.001    0.001 <ipython-input-49-f105717832a2>:1(sum_of_lists)
        1    0.000    0.000    0.001    0.001 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}

*Notes*
* you can profile the memory use of running code by:
    * installing memory_profilier
    * loading the profiler extension ```%load_ext memory_profilier```
    * using the %memit magic 
    
* there are also line-by-line versions of the %prun and %memit magics
    

# Numpy 

In [51]:
import numpy as np

In [54]:
#check version of numpy imported
np.__version__

'1.19.1'

## Python Lists & Numpy Arrays

### Python Integers and Lists 

In [55]:
#in Python integers carry more information than just the integer value
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
#return the type of 0 in L
type(L[0])

int

In [58]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [59]:
type(L2[0])

str

### Python Lists vs. NumPy Arrays

In [60]:
#because python lists are dynamic, we can create heterogeneous lists
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [61]:
#Numpy arrays, unlike Python lists, are not dynamic types, they are fixed-types
#so Numpy arrays are less flexible, but much more efficient

In [64]:
#create a numpy array out of a python list
np.array([1,4,3,5,3])

array([1, 4, 3, 5, 3])

In [65]:
#to explicity set the data type of objects in the array add a dtype argument to the code
np.array([1,4,2,5,3], dtype="float32")

array([1., 4., 2., 5., 3.], dtype=float32)

In [66]:
#np arrays can be multi-dimensional
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Creating Arrays from Scratch

In [67]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [68]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [69]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.95852575, 0.76267456, 0.90586662],
       [0.75957039, 0.77878687, 0.73211598],
       [0.79728514, 0.44235363, 0.27887012]])

In [70]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.0473896 , -0.71752586, -1.52411449],
       [ 0.33979592, -1.44904432, -1.62209571],
       [ 1.52855915,  0.68687744, -0.16819618]])

In [71]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[5, 3, 9],
       [4, 9, 2],
       [2, 5, 9]])

## Array Attributes

In [72]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [73]:
#to see the number of dimensions in an array
x3.ndim

3

In [74]:
#to see the shape (i.e. size of each dimension) of an array
x3.shape

(3, 4, 5)

In [78]:
x3.shape??

Type:        tuple
String form: (3, 4, 5)
Length:      3
Docstring:  
Built-in immutable sequence.

If no argument is given, the constructor returns an empty tuple.
If iterable is specified the tuple is initialized from iterable's items.

If the argument is a tuple, the return value is the same object.


In [79]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
rando = np.random.normal(0, 1, (3, 3))

In [80]:
rando.shape

(3, 3)

In [76]:
#to see number of elements in the array
x3.size

60

In [81]:
# to see byte size of each item in array
x3.itemsize

4

## Working with Arrays 

In [82]:
# to see byte size of the array
x3.nbytes

240

### Indexing

In [83]:
#to see the a specific element in an array, you can use it's index
x1[0]

5

In [88]:
#in multi-dimensionl array, you have to use it's row and column indices
x2[0,0]

3

In [89]:
#you can modify an element using index notation
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

### Slicing

In [90]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
#to access a slice (or sub-array)
x[:5]

array([0, 1, 2, 3, 4])

In [92]:
x[4:7]

array([4, 5, 6])

In [93]:
x[1::2]

array([1, 3, 5, 7, 9])

In [94]:
#to access slice of multi-dimensional arrays
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [95]:
#to access all values in colun 0 of the array
print(x2[:, 0])

[12  7  1]


In [96]:
#in above instances we are just viewing a piece of the array. to copy a piece (so it can be modified without changing the underlying array)
x2_copy = x2[:2, :2].copy()

### Reshaping Arrays

In [98]:
#to put numbers 1-9 into a 3x3 grid
grid = np.arange(1,10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Joining Arrays

In [99]:
#to join two arrays
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [100]:
# you can join three or more arrays as well
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [101]:
#to join multi-dimensional arrays along the first axis (add additional rows?)
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [102]:
#to join along the second axis (add additional columns?)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [103]:
#if joining arrays with different dimensions
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [104]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting Arrays

In [105]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [107]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [108]:
third, axis = np.dsplit(grid, [2])
print(third)
print(axis)

ValueError: dsplit only works on arrays of 3 or more dimensions

## Computation on Arrays

### Arithmetic Operations

In [2]:
#arrays can be added, subtracted, multiplied,etc. 
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) 

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [4]:
#arithmetic operations can also be done using specific numpy functions
np.add(x, 2)

array([2, 3, 4, 5])

In [5]:
#to get the absolute value of an array
x=np.array([-2,-1,0,1,2])
np.absolute(x)

array([2, 1, 0, 1, 2])

In [6]:
#you can also use 
np.abs(x)

array([2, 1, 0, 1, 2])

### Trigonomic Operations

In [10]:
theta = np.linspace(0, np.pi, 3)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [9]:
%pdb

Automatic pdb calling has been turned ON


In [11]:
#for inverse trigonomic functions
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and Logarithms

In [12]:
#to get exponents of arrays
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [13]:
#to get the log (i.e. inverse of exponents)
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


### Specifying Output

In [14]:
#use out= to specify a var or location to hold the result of calculation
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [15]:
#to specify how the result is stored
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


### Aggregating 

In [18]:
df.head

<bound method NDFrame.head of        in-store  age  items   amount  region
0             0   37      4   281.03       2
1             0   35      2   219.51       2
2             1   45      3  1525.70       4
3             1   46      3   715.25       3
4             1   33      4  1937.50       1
...         ...  ...    ...      ...     ...
79995         1   71      3   558.82       1
79996         0   59      7  1932.00       3
79997         0   54      1   414.16       2
79998         1   49      4   335.32       1
79999         1   30      1   527.12       3

[80000 rows x 5 columns]>

In [19]:
df.head()

in-store  age  items   amount  region
0         0   37      4   281.03       2
1         0   35      2   219.51       2
2         1   45      3  1525.70       4
3         1   46      3   715.25       3
4         1   33      4  1937.50       1

In [5]:
#to sum all the value in the age column of df
rdc = np.add.reduce(df[:,1])

TypeError: '(slice(None, None, None), 1)' is an invalid key

In [6]:
x = np.arange(1, 6)
np.add.reduce(x)

15

In [8]:
np.multiply.reduce(x)

120

In [9]:
#to see all the intermediate stages suppressed with reduce, use accumulate
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [10]:
#to get the sum of columns in an array, add axis=0 parameter
df.sum(axis=0)

in-store    4.000000e+04
age         3.660634e+06
items       3.603980e+05
amount      6.687357e+07
region      2.140000e+05
dtype: float64

In [11]:
#to get minimum value in each column
df.min(axis=0)

in-store     0.0000
age         18.0000
items        1.0000
amount       5.0047
region       1.0000
dtype: float64

In [12]:
#to get maximum value in each column
df.max(axis=0)

in-store       1.0
age           85.0
items          8.0
amount      3000.0
region         4.0
dtype: float64

In [13]:
#to get max value in each row
df.max?

Signature: df.max(axis=None, skipna=None, level=None, numeric_only=None, **kwargs)
Docstring:
Return the maximum of the values for the requested axis.

If you want the *index* of the maximum, use ``idxmax``. This isthe equivalent of the ``numpy.ndarray`` method ``argmax``.

Parameters
----------
axis : {index (0), columns (1)}
    Axis for the function to be applied on.
skipna : bool, default True
    Exclude NA/null values when computing the result.
level : int or level name, default None
    If the axis is a MultiIndex (hierarchical), count along a
    particular level, collapsing into a Series.
numeric_only : bool, default None
    Include only float, int, boolean columns. If None, will attempt to use
    everything, then use only numeric data. Not implemented for Series.
**kwargs
    Additional keyword arguments to be passed to the function.

Returns
-------
Series or DataFrame (if level specified)

See Also
--------
Series.sum : Return the sum.
Series.min : Return the minimum.
Ser

In [14]:
df.max(axis=1)

0         281.03
1         219.51
2        1525.70
3         715.25
4        1937.50
          ...   
79995     558.82
79996    1932.00
79997     414.16
79998     335.32
79999     527.12
Length: 80000, dtype: float64

In [18]:
#to return index with max value
np.argmax(df)

82393

In [22]:
#this gives you the median of the age column in the df
np.median(df['age'])

45.0

In [25]:
#you can also get stats of column by creating a variable = to column, then calculating
age = np.array(df['age'])
print('mean', age.mean())
print('median', age.median())
print('std', age.std())

mean 45.757925


AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [26]:
np.median(age)

45.0

In [17]:
#missing value-safe aggregating functions are the same, but ignore missing values
np.nansum(df, axis=0)

array([4.00000000e+04, 3.66063400e+06, 3.60398000e+05, 6.68735736e+07,
       2.14000000e+05])

In [28]:
%matplotlib?

Docstring:
::

  %matplotlib [-l] [gui]

Set up matplotlib to work interactively.

This function lets you activate matplotlib interactive support
at any point during an IPython session. It does not import anything
into the interactive namespace.

If you are using the inline matplotlib backend in the IPython Notebook
you can set which figure formats are enabled using the following::

    In [1]: from IPython.display import set_matplotlib_formats

    In [2]: set_matplotlib_formats('pdf', 'svg')

The default for inline figures sets `bbox_inches` to 'tight'. This can
cause discrepancies between the displayed image and the identical
image created using `savefig`. This behavior can be disabled using the
`%config` magic::

    In [3]: %config InlineBackend.print_figure_kwargs = {'bbox_inches':None}

In addition, see the docstring of
`IPython.display.set_matplotlib_formats` and
`IPython.display.set_matplotlib_close` for more information on
changing additional behaviors of the inline backend.
